### ISSUE TITLE
CSS Targeting

### ISSUE THREAD

**Issue by melissamcewen** [craigthekorean/Dasmoto-CSS#4]
My approach to CSS is 
1. Things that apply to entire document (target `<body>` see https://css-tricks.com/html-vs-body-in-css/)
2. Things that apply to common elements (tags like `<h2>`, `<p>`) of the document
3. Things that apply to specific elements of the document - these are things with CSS classes
4. Things that apply only once - these are things with CSS IDs, note this step is optional and many just use classes

A sign that you can use more of 2 or 3 is repeating the same properties and values over and over again like
```css
#brush {
  background-color: mediumspringgreen;
  font-size: 32px;
  color: white;
}

#frame {
  background-color: lightcoral;
  font-size: 32px;
  color: white;

}

#paint {
  background-color: skyblue;
  font-size: 32px;
  color: white;

}


```
Instead we can use
```css
h2 {
  font-size: 32px;
  color: white;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```

Here is a good template to get you started with this: 

``` css
html {
  /* apply the font to the entire page, then you can remove font from the other classes */ 
}

/* common HTML elements */ 


h1 {

}

h2 {
/* What do these all share? One thing is color but there are others */ 
}

/* These are classes applied several times on the page */ 

.price {
}

/* these are classes only used once, you can use IDs too */ 

.paint {
}

.brush {
}

.frame {
}

```

This should also take care of all the places where the font doesn't match the spec, because once you apply Helvetica to body, it applies to the whole page just like in the spec! Hooray!
